In [2]:
import numpy as np

In [4]:
# 1
vector = np.arange(10, 50) 
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
#2
matrix = np.arange(0, 9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
#3
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#4
np.random.randint(0, 10, (3, 3, 3))

array([[[5, 3, 9],
        [4, 2, 0],
        [3, 7, 9]],

       [[2, 5, 9],
        [7, 2, 2],
        [9, 0, 0]],

       [[8, 7, 1],
        [2, 8, 4],
        [2, 5, 5]]], dtype=int32)

In [15]:
#5
array_10 = np.random.randint(0,21,(10,10))

maxnum = array_10.max()
minnum = array_10.min()

print(array_10)
print("Max number:", maxnum)
print("Min number:", minnum)    

[[16 10 15  8  1 16 18 17  2 18]
 [ 0 14  5  9 18 11  7  9  6 18]
 [ 1 20 14 12 20 19  1  9  8  2]
 [ 1 20 11  9 18 12  8  5 15 18]
 [11 11  3 16 15 15 11  3  2 14]
 [ 2 14  7 17  6  1 18  3 20  3]
 [14  8  3 16  5 17  2  9 17  5]
 [19  7  5  8  3 13 12 13  8  8]
 [ 8 12  2  2 15 15  8  8  0 10]
 [ 8  8 10 15 12 14 11  1 11  5]]
Max number: 20
Min number: 0


In [18]:
#6
random_vec = np.random.rand(30)

mean = random_vec.mean()

print(mean)

0.47138268924034726


In [19]:
#7
matrix = np.random.rand(5, 5)

normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print("Original Matrix:\n", matrix)
print("\nNormalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.60666267 0.30740228 0.77256216 0.92421447 0.07000433]
 [0.26375816 0.24123983 0.20216737 0.10454434 0.35954248]
 [0.42994094 0.01039923 0.52323163 0.91919661 0.5795934 ]
 [0.46636864 0.26481761 0.09141127 0.91257928 0.12123207]
 [0.33512395 0.05635848 0.36613535 0.69966082 0.30991008]]

Normalized Matrix:
 [[0.6524989  0.32501434 0.83404489 1.         0.06522665]
 [0.277254   0.2526119  0.20985439 0.10302423 0.38207204]
 [0.45911    0.         0.56119922 0.99450889 0.62287664]
 [0.49897331 0.27841338 0.08865254 0.98726746 0.12128583]
 [0.35535052 0.05029381 0.3892867  0.754268   0.32775865]]


In [21]:
#8 
matrix_5_3 = np.random.rand(5, 3)
matrix_3_2 = np.random.rand(3, 2)
result = matrix_5_3 @ matrix_3_2
result

array([[0.55324483, 0.93012404],
       [0.51197127, 0.92109555],
       [0.86516932, 1.36121369],
       [0.52098254, 0.98294878],
       [0.37606057, 0.64991647]])

In [23]:
#9
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3) 
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)   
result = np.dot(matrix1, matrix2)
result

Matrix 1:
 [[0.28392903 0.34490218 0.09631838]
 [0.59030139 0.84121304 0.96288565]
 [0.00159441 0.11056177 0.82020539]]
Matrix 2:
 [[0.14839523 0.16066497 0.41577702]
 [0.4141168  0.18927271 0.47081611]
 [0.2524157  0.35871541 0.94502591]]


array([[0.20927577, 0.14544891, 0.37146004],
       [0.67900582, 0.59946135, 1.55144229],
       [0.2530548 , 0.31540281, 0.82783253]])

In [24]:
#10
matrix = np.random.rand(4, 4)
print("Original Matrix:\n", matrix)
transposed_one = matrix.T
print("\nTransposed Matrix:\n", transposed_one)

Original Matrix:
 [[0.0211108  0.66043263 0.69752036 0.43287262]
 [0.65230961 0.88914876 0.7125016  0.96420673]
 [0.7805454  0.24785373 0.32041704 0.35558476]
 [0.79280463 0.41481471 0.61820681 0.29682761]]

Transposed Matrix:
 [[0.0211108  0.65230961 0.7805454  0.79280463]
 [0.66043263 0.88914876 0.24785373 0.41481471]
 [0.69752036 0.7125016  0.32041704 0.61820681]
 [0.43287262 0.96420673 0.35558476 0.29682761]]


In [26]:
#11
matrix = np.random.rand(3, 3)
determinant = np.linalg.det(matrix)
print("Matrix:\n", matrix)
print("Determinant:", determinant)

Matrix:
 [[0.74004231 0.79277459 0.51940121]
 [0.05364613 0.8454568  0.38931693]
 [0.56972744 0.19684739 0.55559129]]
Determinant: 0.19841689827013262


In [ ]:
#12

A = np.random.rand(3, 4) 
B = np.random.rand(4, 3)  
print("Matrix A:\n", A)
print("Matrix B:\n", B)
result = np.dot(A, B)
print("Result:\n", result)

Matrix A:
 [[0.18294421 0.15068303 0.09977491 0.53420182]
 [0.32489569 0.85285533 0.55258227 0.56676235]
 [0.81752991 0.70597912 0.92121397 0.02756456]]
Matrix B:
 [[0.53791864 0.33378746 0.33139827]
 [0.00280729 0.70658661 0.91983827]
 [0.95266823 0.41214152 0.91186483]
 [0.45612581 0.99213287 0.58248202]]
Result:
 [[0.43754774 0.73865566 0.6013756 ]
 [0.96210418 1.50110792 1.72616806]
 [1.33193065 1.17873485 1.77639309]]


In [ ]:
#13
matrix = np.random.rand(3, 3)

vector = np.random.rand(3, 1)

result = matrix @ vector 

print("Matrix (3x3):\n", matrix)
print("\nColumn Vector (3x1):\n", vector)
print("\nResultant Matrix-Vector Product (3x1):\n", result)


Matrix (3x3):
 [[0.42542011 0.04572771 0.14786539]
 [0.05397821 0.34559562 0.32335495]
 [0.76427444 0.64042099 0.35720765]]

Column Vector (3x1):
 [[0.23672606]
 [0.54830512]
 [0.15446221]]

Resultant Matrix-Vector Product (3x1):
 [[0.14862038]
 [0.25221601]
 [0.58724486]]


In [38]:
#14
A = np.random.rand(3, 3)

b = np.random.rand(3, 1)

x = np.linalg.solve(A, b)

print("Matrix A (3x3):\n", A)
print("\nColumn Vector b (3x1):\n", b)
print("\nSolution x (3x1):\n", x)

Matrix A (3x3):
 [[0.89647937 0.49391455 0.7028465 ]
 [0.45713866 0.7010929  0.58321162]
 [0.41767363 0.82998018 0.34430445]]

Column Vector b (3x1):
 [[0.92683101]
 [0.0021132 ]
 [0.41624333]]

Solution x (3x1):
 [[ 2.70999711]
 [ 0.03476443]
 [-2.16234435]]


In [ ]:
#15
matrix_5_5 = np.random.randint(1,6,(5, 5))

row_wise_sum = matrix_5_5.sum(axis=1)
column_wise_sum = matrix_5_5.sum(axis=0)

print("Matrix (5x5):\n", matrix_5_5)
print("\nRow-wise sum:\n", row_wise_sum)
print("\nColumn-wise sum:\n", column_wise_sum)

Matrix (5x5):
 [[5 2 3 5 2]
 [4 5 4 4 3]
 [1 3 2 2 5]
 [2 5 4 4 4]
 [1 2 3 3 3]]

Row-wise sum:
 [17 20 13 19 12]

Column-wise sum:
 [13 17 16 18 17]
